# Generated by Django 6.0.2 on 2026-03-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "pmc_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary_basic", models.TextField()),
                ("summary_college", models.TextField()),
                ("summary_professional", models.TextField()),
            ],
        ),
    ]
