# Generated by Django 6.0.2 on 2026-03-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summary",
            name="title",
        ),
    ]
