# Generated by Django 6.0.2 on 2026-03-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer_app", "0002_remove_summary_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summary",
            old_name="summary_basic",
            new_name="basic_summary",
        ),
        migrations.RenameField(
            model_name="summary",
            old_name="summary_college",
            new_name="college_summary",
        ),
        migrations.RenameField(
            model_name="summary",
            old_name="summary_professional",
            new_name="professional_summary",
        ),
    ]
